### PR TITLE
Add a 'fast'-mode, surpassing robustness code

### PR DESCRIPTION
**Pull request by berland**
In normal mode: WaterOilGas construction and SWOF+SGOF: 66 ms
In fast mode: 36 ms

### CODE REVIEW

**Comment by berland** [comment]
Solving #56

**Comment by wouterjdb** [comment]
After testing the latest release I immediately get the following error when launching Flow:

```
**********************************************************************
*                                                                    *
*                        This is flow 2019.04                        *
*                                                                    *
* Flow is a simulator for fully implicit three-phase black-oil flow, *
*             including solvent and polymer capabilities.            *
*          For more information, see https://opm-project.org         *
*                                                                    *
**********************************************************************

Reading deck file 'REALIZATION.DATA'
Failed to create valid EclipseState object.
Exception caught: Incorrect ordering of values in column: SW
terminate called after throwing an instance of 'std::invalid_argument'
  what():  Incorrect ordering of values in column: SW
 *** Process received signal ***
Signal: Aborted (6)
Signal code:  (-6)
[ 0] /lib/x86_64-linux-gnu/libpthread.so.0(+0x12dd0)[0x7ff1183b5dd0]
[ 1] /lib/x86_64-linux-gnu/libc.so.6(gsignal+0xc7)[0x7ff11710f077]
```

In many generated curves I see things like:
```
0.8089566 1.0000000 0.0000000 0
0.8289566 1.0000000 0.0000000 0
0.8489566 1.0000000 0.0000000 0
0.8689566 1.0000000 0.0000000 0
0.8889566 1.0000000 0.0000000 0
0.9089566 1.0000000 0.0000000 0
0.4881341 1.0000000 0.0000000 0 <----------------
0.9242651 1.0000000 0.0000000 0
```

or

```
0.6229754 0.4854626 0.4402682 0
0.6429754 0.5668283 0.3870695 0
0.6629754 0.6555857 0.3287643 0
0.6829754 0.7519078 0.2629841 0
0.7029754 0.8559613 0.1844218 0
0.7229754 0.9679073 0.0719637 0
0.3259170 0.0000000 1.0000000 0 <----------------
0.7284590 1.0000000 0.0000000 0
1.0000000 1.0000000 0.0000000 0
```

This happens both for `SGOF` and `SWOF`.

**Comment by berland** [comment]
Version 0.2.1 is retracted. 

Do you have the pyscal codelines that produced this particular output? (endpoints, h, and corey parameters)

**Comment by wouterjdb** [comment]
Seems like the incorrectly ordered number is the `swcr`. For the gas curves it is `sorg+sgcr`.
```
SWOF
-- 
-- Sw Krw Krow Pc
-- swirr=0.0105817 swl=0.0799711 swcr=0.310624 sorw=0.210718
-- Corey krw, nw=1.77484, krwend=1, krwmax=1
-- Corey krow, now=0.730026, kroend=1, kromax=1
-- Zero capillary pressure
0.0799711 0.0000000 1.0000000 0
0.0999711 0.0000000 0.9988089 0
0.1199711 0.0000000 0.9976177 0
0.1399711 0.0000000 0.9964266 0
0.1599711 0.0000000 0.9952355 0
0.1799711 0.0000000 0.9940443 0
0.1999711 0.0000000 0.9928532 0
0.2199711 0.0000000 0.9916620 0
0.2399711 0.0000000 0.9904709 0
0.2599711 0.0000000 0.9892798 0
0.2799711 0.0000000 0.9880886 0
0.2999711 0.0000000 0.9868975 0
0.3199711 0.0009251 0.9857064 0
0.3399711 0.0070482 0.9548608 0
0.3599711 0.0177277 0.9236422 0
0.3799711 0.0324276 0.8920284 0
0.3999711 0.0508440 0.8599945 0
0.4199711 0.0727680 0.8275130 0
0.4399711 0.0980424 0.7945529 0
0.4599711 0.1265422 0.7610790 0
0.4799711 0.1581641 0.7270514 0
0.4999711 0.1928207 0.6924240 0
0.5199711 0.2304365 0.6571438 0
0.5399711 0.2709454 0.6211483 0
0.5599711 0.3142882 0.5843637 0
0.5799711 0.3604121 0.5467014 0
0.5999711 0.4092691 0.5080533 0
0.6199711 0.4608155 0.4682845 0
0.6399711 0.5150111 0.4272235 0
0.6599711 0.5718187 0.3846453 0
0.6799711 0.6312039 0.3402430 0
0.6999711 0.6931344 0.2935775 0
0.7199711 0.7575804 0.2439747 0
0.7399711 0.8245135 0.1902848 0
0.7599711 0.8939071 0.1301611 0
0.7799711 0.9657362 0.0563509 0
0.3106240 0.0000000 1.0000000 0 <---------------------- marked red in plot
0.7892820 1.0000000 0.0000000 0
1.0000000 1.0000000 0.0000000 0
/
```
Plot of the curve above:
image

**Pull request merged**
