### PR TITLE
Read csv file with utf-8 mode

### PR DESCRIPTION
**Pull request by alifbe**
Fix issue with reading CSV file without utf-8 in Windows environment

### CODE REVIEW

**Comment by berland** [comment]
Is there a test confirming that it now works on Windows?

**Comment by alifbe** [comment]
@berland Yes, the existing test is actually served the purpose here. I have removed the skip attribute for Windows and as you see, it passed the test.

**Comment by berland** [comment]
There is no removal of a skip attribute in this PR..?

**Comment by alifbe** [comment]
Yes, the removal is actually done in previous [PR ](https://github.com/equinor/pyscal/pull/398)

Due to the merge with the other [PR](https://github.com/equinor/pyscal/pull/396) it failed the test. This PR is trying to solve it 😄

**Pull request merged**
