### PR TITLE
Adapt interactive_tests.py to pytest

### PR DESCRIPTION
**Pull request by berland**
Also deleted some tests that are now covered by automatic tests.

### CODE REVIEW

**Comment by lars-petter-hauge** [comment]
Can I ask the reason for making tests that will have to be verified manually?

**Comment by berland** [comment]
> Can I ask the reason for making tests that will have to be verified manually?

All important parts of the code is covered by automatic tests, so doing this interactive tests is not critical (this statement is valid until proven otherwise). But the plots themselves might have or get visual bugs, and these are hard to detect automatically.

**Comment by lars-petter-hauge** [comment]
Suppose this is because you're using random numbers to generate input? Otherwise asserting to known values should provide testing against what `pyscal` does (guessing this is already done). Perhaps property testing (see the python library `hypothesis`) would be a possible way to go, where all input data are randomly made. It requires you to reconsider how you do your assertions.

Just make sure we're testing `pyscal` and not `matplotlib` :)

**Review by lars-petter-hauge — APPROVED** [review]

**Comment by berland** [comment]
`hypothesis` is already an extremely critical part of the pyscal CI 👍🏻

**Pull request merged**
