### PR TITLE
Remove SGCR from GasWater parametrization

### PR DESCRIPTION
**Pull request by berland**

### CODE REVIEW

**Review by eivindsm — COMMENTED** [review]
The PR looks good in technical terms, but I wonder what the rationale for removing sgcr in the first place. Is it redundant and can be replaced by other means?

**Comment by berland** [comment]
@richypitman, would you like to chip in?

**Comment by richypitman** [comment]
A critical gas saturation is not the same as a residual gas saturation and 'residual' and 'critical' should not be used interchangeably. This causes confusion when delivering SCAL models. What has previously been called 'sgcr' in gas water models is actually the residual (trapped) gas saturation. We call this Sgrw (residual gas saturation after water invasion) in the SCAL group and I think that's pretty standard notation within core analysis. I've also seen 'Sgt'. More comments [here](https://github.com/equinor/pyscal/issues/257#issuecomment-820960746).

**Comment by berland** [comment]
Aside endpoint naming, this PR removes one degree of freedom for the GasWater relperm curves, both `krw` and `krg` now share the endpoint `sgrw`

**Comment by berland** [comment]
todo: remove sgcr from interactive_tests.py

**Review by eivindsm — COMMENTED** [review]
Ref email from @vkip ; it seems we do not fully agree on the nomenclature. I think we should, and I propose asking @vkip for approving this PR.

**Comment by berland** [comment]
Removing sgcr from parametrization removes the possibility for modelling paleozones and gas remobilization (@vkip ). Won't merge.

**Pull request closed without merging**
