### PR TITLE
Allow negative swirr values (-1 <= swirr <= 1)

### LINKED ISSUE #408: Allow negative swirr values
Negative swirr values are currently not allowed. I suggest we remove this restriction as using negative swirr values is a very convenient and simple way of adding uncertainty to the initial water saturation.

Looks like this can be achieved by editing these these lines:

https://github.com/equinor/pyscal/blob/072bba61749f12bad24c86bcb053a73fd13fdea8/pyscal/wateroil.py#L80

https://github.com/equinor/pyscal/blob/072bba61749f12bad24c86bcb053a73fd13fdea8/pyscal/gasoil.py#L76

### PR DESCRIPTION
**Pull request by rnyb**
Resolves #408

### CODE REVIEW

**Review by mferrera — APPROVED** [review]
LGTM 👍

**Comment by mferrera** [comment]
Should any tests be changed or added for this?

**Review by alifbe — APPROVED** [review]
I see how useful it is to relax the constraint of Swirr to allow it goes under zero.

We should consider printing a warning when user is using negative Swirr since it's not a "mainstream"

**Review by alifbe — APPROVED** [review]
Nice. Thanks for the update @rnyb

**Pull request merged**
