### PR TITLE
Add parameter SOCR for use in oil paleo zone modelling

### PR DESCRIPTION
**Pull request by berland**
Made on top of #268 and #270. Look only at last commit for review.

https://github.com/equinor/pyscal/blob/77c6130640a9b764debc326082ea974366ed57d7/docs/images/wateroil-idc1_paleooil.png

### CODE REVIEW

**Comment by berland** [comment]
Rebased and ready

**Review by lars-petter-hauge — APPROVED** [review]
Looks good!

Could add a test checking that being epsilon away from `sorw` leads to `socr = sorw` (and warning generated)

**Comment by berland** [comment]
@vkip, good to go?

**Comment by berland** [comment]
> Could add a test checking that being epsilon away from `sorw` leads to `socr = sorw` (and warning generated)

Good idea. Also made a check to error if `socr < sorw`.

**Review by vkip — APPROVED** [review]
Good to go!

**Pull request merged**
